#!/bin/bash
# WorkDir=$(pwd)
# echo $WorkDir

# Dir=$(find /home/jdoi/cpp/ -name "$1.cpp")
# echo Completely find $1.cpp at $Dir
# rm -rf /home/jdoi/cpp/OI/1
# echo Completely delete old file
# g++ $Dir -o /home/jdoi/cpp/OI/1 -fsanitize=undefined,signed-integer-overflow,address -Wall -std=c++14 -g -fdiagnostics-color=always
# echo g++ Complete
echo Ready to debug...
gdb /home/jdoi/cpp/OI/1